export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  BARBER = 'BARBER',
  ADMIN = 'ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export enum BarberStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
}

export enum BarberPreference {
  ANY = 'ANY',
  SPECIFIC = 'SPECIFIC',
}

export enum ServiceStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum AllocationFailureReason {
  NO_BARBER_WITHIN_RADIUS = 'NO_BARBER_WITHIN_RADIUS',
  NO_SERVICE_PROVIDER = 'NO_SERVICE_PROVIDER',
  NO_AVAILABLE_SLOT = 'NO_AVAILABLE_SLOT',
  ALL_BARBERS_EXCLUDED = 'ALL_BARBERS_EXCLUDED',
  NO_AUTO_ALLOCATION_BARBER = 'NO_AUTO_ALLOCATION_BARBER',
  STALE_LOCATION = 'STALE_LOCATION',
  MAX_ATTEMPTS_REACHED = 'MAX_ATTEMPTS_REACHED',
}
